import type { Metadata } from "next";
import "./globals.css";
import GNBWrapper from "./_components/GNBWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-normal text-normal">
        <GNBWrapper />
        {children}
      </body>
    </html>
  );
}
